#!/bin/bash
#This project is to determine how best to resolvethe war between Russia and Ukrian
#it is important to note that all contributins should be neutral.
#feel free to opt out if you have any bias or conflicting issue that might affect your descion from being neutral
