#!/bin/bash
#it is our duty to restore peace to waring contries
#we must ensure that there is no threath to life of the people living in these affected countries
#food, clothings and medical supplies should be made available to these affected countries.
