#!/bin/bash
#Delegates should be sent to Russia to meet the presidents Council in December
#Delegates sent should sign a non-disclosure agreement
#all members of this cabinet should report directly to Didi
